import 'package:flutter/material.dart';

import '../../services/dashboard_state.dart';
import '../../theme/app_theme.dart';
import '../common/explorer_empty_state.dart';
import '../remediation_plan.dart';

import 'manual_query_bar.dart';
import 'dashboard_card_wrapper.dart';

/// Dashboard panel showing all collected remediation plans.
class LiveRemediationPanel extends StatelessWidget {
  final List<DashboardItem> items;
  final DashboardState dashboardState;
  const LiveRemediationPanel({
    super.key,
    required this.items,
    required this.dashboardState,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(12, 8, 12, 4),
          child: ManualQueryBar(
            hintText: 'Search plans...',
            initialValue: dashboardState.getLastQueryFilter(DashboardDataType.remediation),
            isLoading: dashboardState.isLoading(DashboardDataType.remediation),
            onSubmit: (query) {
              dashboardState.setLastQueryFilter(DashboardDataType.remediation, query);
            },
          ),
        ),
        Expanded(
          child: items.isEmpty
              ? const ExplorerEmptyState(
                  icon: Icons.build_circle_outlined,
                  title: 'No Remediation Plans',
                  description:
                      'Remediation plans are generated by the agent\nduring incident investigations.',
                )
              : ListView.builder(
                  padding: const EdgeInsets.all(12),
                  itemCount: items.length,
                  itemBuilder: (context, index) {
                    final item = items[index];
                    if (item.remediationPlan == null) return const SizedBox.shrink();

                    return DashboardCardWrapper(
                      onClose: () => dashboardState.removeItem(item.id),
                      header: Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(4),
                            decoration: BoxDecoration(
                              color: AppColors.secondaryPurple
                                  .withValues(alpha: 0.15),
                              borderRadius: BorderRadius.circular(6),
                            ),
                            child: const Icon(
                              Icons.build_circle_outlined,
                              size: 14,
                              color: AppColors.secondaryPurple,
                            ),
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              item.remediationPlan!.issue,
                              style: const TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.w600,
                                color: AppColors.textPrimary,
                              ),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ],
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Padding(
                            padding: const EdgeInsets.fromLTRB(12, 0, 12, 8),
                            child: _buildRiskBadge(item.remediationPlan!.risk),
                          ),
                          Padding(
                            padding: const EdgeInsets.all(8),
                            child: RemediationPlanWidget(plan: item.remediationPlan!),
                          ),
                        ],
                      ),
                    );
                  },
                ),
        ),
      ],
    );
  }

  Widget _buildRiskBadge(String risk) {
    Color color;
    switch (risk.toLowerCase()) {
      case 'high':
        color = AppColors.error;
        break;
      case 'medium':
        color = AppColors.warning;
        break;
      default:
        color = AppColors.success;
    }
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.15),
        borderRadius: BorderRadius.circular(6),
        border: Border.all(color: color.withValues(alpha: 0.3)),
      ),
      child: Text(
        risk.toUpperCase(),
        style: TextStyle(
          fontSize: 10,
          fontWeight: FontWeight.w600,
          color: color,
        ),
      ),
    );
  }
}
