steps:
  # 1. Deploy Agent Engine Backend (Parallel Track A)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    waitFor: ['-'] # Start immediately
    entrypoint: 'bash'
    secretEnv: ['SRE_AGENT_ENCRYPTION_KEY', 'GOOGLE_CUSTOM_SEARCH_API_KEY', 'GITHUB_TOKEN']
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - 'GOOGLE_CLOUD_LOCATION=$_LOCATION'
      - 'AGENT_ENGINE_LOCATION=$_LOCATION'
      - 'GOOGLE_CLOUD_STORAGE_BUCKET=$_BUCKET'
      - 'STRICT_EUC_ENFORCEMENT=false'
      - 'SRE_AGENT_ENFORCE_POLICY=false'
      - 'GOOGLE_CUSTOM_SEARCH_ENGINE_ID=$_GOOGLE_CUSTOM_SEARCH_ENGINE_ID'
      - 'GITHUB_REPO=$_GITHUB_REPO'
      - 'SRE_AGENT_COUNCIL_ORCHESTRATOR=$_SRE_AGENT_COUNCIL_ORCHESTRATOR'
      - 'SRE_AGENT_SLIM_TOOLS=$_SRE_AGENT_SLIM_TOOLS'
    args:
      - '-c'
      - |
        # Install uv using the newer recommended path and avoiding cargo/env issues
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="/builder/home/.local/bin:$$PATH"

        uv python install 3.12
        uv sync

        echo "🚀 Updating Agent Engine (Patching existing agent if found)..."
        # Deploy checks for existing agent by name 'sre_agent' and updates it
        uv run python deploy/deploy.py --create

  # 2. Fetch Agent Engine Resource ID (Parallel Track B - Fast)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'fetch-resource-id'
    waitFor: ['-'] # Start immediately
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install jq
        apt-get update && apt-get install -y jq

        # Fast lookup using REST API to avoid waiting for uv/python environment
        echo "🔍 Looking up stable Agent ID..."
        TOKEN=$(gcloud auth print-access-token)
        RESOURCE_NAME=$(curl -s -X GET \
          -H "Authorization: Bearer $$TOKEN" \
          "https://$_LOCATION-aiplatform.googleapis.com/v1/projects/$PROJECT_ID/locations/$_LOCATION/reasoningEngines" \
          | jq -r '.reasoningEngines[] | select(.displayName == "sre_agent") | .name' | head -n 1)

        if [ -z "$$RESOURCE_NAME" ] || [ "$$RESOURCE_NAME" = "null" ]; then
           echo "❌ Agent 'sre_agent' not found. Please deploy manually once first."
           exit 1
        fi
        echo "$$RESOURCE_NAME" > backend_resource_name.txt
        echo "✅ Found Agent: $$RESOURCE_NAME"




  # 4. Build Unified Docker Image (Parallel Track B)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    waitFor: ['fetch-resource-id']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RESOURCE_NAME=$(cat backend_resource_name.txt)
        # Construct the Agent URL
        # Extract location from resource name
        LOCATION=$(echo $$RESOURCE_NAME | cut -d'/' -f4)
        AGENT_URL="https://$$LOCATION-aiplatform.googleapis.com/v1/$$RESOURCE_NAME:query"

        docker build -t gcr.io/$PROJECT_ID/autosre:latest \
          --build-arg SRE_AGENT_URL=$$AGENT_URL \
          --build-arg SRE_AGENT_ID=$$RESOURCE_NAME \
          --build-arg BUILD_SHA=$SHORT_SHA \
          --build-arg BUILD_TIMESTAMP=$$(date -u +%Y-%m-%dT%H:%M:%SZ) .

  # 5. Push Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    waitFor: ['build-image']
    args: ['push', 'gcr.io/$PROJECT_ID/autosre:latest']

  # 6. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    waitFor: ['push-image']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RESOURCE_NAME=$(cat backend_resource_name.txt)
        LOCATION=$(echo $$RESOURCE_NAME | cut -d'/' -f4)
        AGENT_URL="https://$$LOCATION-aiplatform.googleapis.com/v1/$$RESOURCE_NAME:query"

        gcloud run deploy autosre \
          --image gcr.io/$PROJECT_ID/autosre:latest \
          --region $$LOCATION \
          --platform managed \
          --allow-unauthenticated \
          --memory 16Gi \
          --cpu 4 \
          --set-env-vars="WEB_CONCURRENCY=1,SRE_AGENT_URL=$$AGENT_URL,SRE_AGENT_ID=$$RESOURCE_NAME,GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=$$LOCATION,LOG_FORMAT=JSON,LOG_LEVEL=INFO,OTEL_SERVICE_NAME=sre-agent-api,OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true,OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=true,ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS=false,ADK_OTEL_TO_CLOUD=true,OTEL_TO_CLOUD=true,SRE_AGENT_ENFORCE_POLICY=false" \
          --set-secrets="GOOGLE_API_KEY=gemini-api-key:latest,GEMINI_API_KEY=gemini-api-key:latest,GOOGLE_CLIENT_ID=google-client-id:latest,SRE_AGENT_ENCRYPTION_KEY=sre-agent-encryption-key:latest"

  # 7. Run World-Class Eval Suite (Post-Deployment Quality Check)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-evals'
    allowFailure: true
    waitFor: ['deploy-frontend'] # Run AFTER deployment to avoid blocking the release
    entrypoint: 'bash'
    secretEnv: ['SRE_AGENT_ENCRYPTION_KEY', 'GOOGLE_CUSTOM_SEARCH_API_KEY', 'GITHUB_TOKEN', 'EVAL_PROJECT_ID']
    env:
      - 'FALLBACK_PROJECT_ID=$PROJECT_ID'
      - 'GOOGLE_CLOUD_LOCATION=$_LOCATION'
      - 'RUNNING_IN_AGENT_ENGINE=true'
      - 'STRICT_EUC_ENFORCEMENT=false'
      - 'SRE_AGENT_ENFORCE_POLICY=false'
      - 'GOOGLE_CUSTOM_SEARCH_ENGINE_ID=$_GOOGLE_CUSTOM_SEARCH_ENGINE_ID'
      - 'GITHUB_REPO=$_GITHUB_REPO'
    args:
      - '-c'
      - |
        # Use EVAL_PROJECT_ID from secret if available, otherwise fallback to build project
        export GOOGLE_CLOUD_PROJECT=$${EVAL_PROJECT_ID:-$$FALLBACK_PROJECT_ID}
        echo "📍 Using Project ID: $$GOOGLE_CLOUD_PROJECT"

        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="/builder/home/.local/bin:$$PATH"
        uv python install 3.12
        uv sync

        echo "📊 Running SRE Agent Evaluation Suite (Asynchronous Quality Gate)..."
        # We run evals against the local code to verify logic before final release
        uv run poe eval

substitutions:
  _LOCATION: us-central1
  _BUCKET: your-staging-bucket-name
  _GOOGLE_CUSTOM_SEARCH_ENGINE_ID: ""
  _GITHUB_REPO: "srtux/sre-agent"
  _SRE_AGENT_COUNCIL_ORCHESTRATOR: ""
  _SRE_AGENT_SLIM_TOOLS: ""

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sre-agent-encryption-key/versions/latest
    env: 'SRE_AGENT_ENCRYPTION_KEY'
  - versionName: projects/$PROJECT_ID/secrets/google-custom-search-api-key/versions/latest
    env: 'GOOGLE_CUSTOM_SEARCH_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
    env: 'GITHUB_TOKEN'
  # Setup this secret if you want to run evals against a different project than the build project
  - versionName: projects/$PROJECT_ID/secrets/eval-project-id/versions/latest
    env: 'EVAL_PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
