steps:
  # 1. Install uv and Python dependencies
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'install-dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        source $$HOME/.cargo/env
        uv python install 3.10
        uv sync

  # 2. Fetch Agent Engine Resource ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'fetch-resource-id'
    entrypoint: 'bash'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - 'GOOGLE_CLOUD_LOCATION=$_LOCATION'
      - 'AGENT_ENGINE_LOCATION=$_LOCATION'
      - 'GOOGLE_CLOUD_STORAGE_BUCKET=$_BUCKET'
    args:
      - '-c'
      - |
        source $$HOME/.cargo/env
        # Fetch the existing stable resource ID
        uv run python deploy/get_id.py > backend_resource_name.txt

        if [ ! -s backend_resource_name.txt ]; then
           echo "❌ Agent not found. Cannot parallelize. Please deploy manually first."
           exit 1
        fi
        echo "✅ Found Agent: $(cat backend_resource_name.txt)"

  # 3. Deploy Agent Engine Backend (Parallel Track A)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    waitFor: ['-'] # Start immediately in parallel
    entrypoint: 'bash'
    secretEnv: ['SRE_AGENT_ENCRYPTION_KEY']
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - 'GOOGLE_CLOUD_LOCATION=$_LOCATION'
      - 'AGENT_ENGINE_LOCATION=$_LOCATION'
      - 'GOOGLE_CLOUD_STORAGE_BUCKET=$_BUCKET'
      # Ensure backend has the key to decrypt user tokens
      - 'STRICT_EUC_ENFORCEMENT=false'
    args:
      - '-c'
      - |
        source $$HOME/.cargo/env
        echo "🚀 Updating Agent Engine (Patching existing agent if found)..."
        # Deploy checks for existing agent by name 'sre_agent' and updates it
        uv run python deploy/deploy.py --create

  # 4. Build Unified Docker Image (Parallel Track B)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    waitFor: ['fetch-resource-id']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RESOURCE_NAME=$(cat backend_resource_name.txt)
        # Construct the Agent URL
        # Extract location from resource name
        LOCATION=$(echo $$RESOURCE_NAME | cut -d'/' -f4)
        AGENT_URL="https://$$LOCATION-aiplatform.googleapis.com/v1/$$RESOURCE_NAME:query"

        docker build -t gcr.io/$PROJECT_ID/autosre:latest \
          --build-arg SRE_AGENT_URL=$$AGENT_URL \
          --build-arg SRE_AGENT_ID=$$RESOURCE_NAME .

  # 5. Push Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    waitFor: ['build-image']
    args: ['push', 'gcr.io/$PROJECT_ID/autosre:latest']

  # 6. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    waitFor: ['push-image']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RESOURCE_NAME=$(cat backend_resource_name.txt)
        LOCATION=$(echo $$RESOURCE_NAME | cut -d'/' -f4)
        AGENT_URL="https://$$LOCATION-aiplatform.googleapis.com/v1/$$RESOURCE_NAME:query"

        gcloud run deploy autosre \
          --image gcr.io/$PROJECT_ID/autosre:latest \
          --region $$LOCATION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="SRE_AGENT_URL=$$AGENT_URL,SRE_AGENT_ID=$$RESOURCE_NAME,GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=$$LOCATION,LOG_FORMAT=JSON,LOG_LEVEL=INFO" \
          --set-secrets="GOOGLE_API_KEY=gemini-api-key:latest,GEMINI_API_KEY=gemini-api-key:latest,GOOGLE_CLIENT_ID=google-client-id:latest,SRE_AGENT_ENCRYPTION_KEY=sre-agent-encryption-key:latest"

substitutions:
  _LOCATION: us-central1
  _BUCKET: your-staging-bucket-name

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sre-agent-encryption-key/versions/latest
    env: 'SRE_AGENT_ENCRYPTION_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
