"""Pydantic schemas for Code Execution Sandbox.

This module defines schemas for Agent Engine Code Execution sandbox operations,
used for processing large volumes of data in isolated environments.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class SandboxLanguage(str, Enum):
    """Supported languages for code execution."""

    PYTHON = "LANGUAGE_PYTHON"
    JAVASCRIPT = "LANGUAGE_JAVASCRIPT"


class MachineConfig(str, Enum):
    """Machine configurations for sandbox execution."""

    DEFAULT = "MACHINE_CONFIG_DEFAULT"  # 2 vCPU, 1.5 GB RAM
    VCPU4_RAM4GIB = "MACHINE_CONFIG_VCPU4_RAM4GIB"  # 4 vCPU, 4 GB RAM


class SandboxFile(BaseModel):
    """A file to be passed to or returned from the sandbox."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(description="File name within the sandbox")
    content: bytes = Field(description="File content as bytes")


class SandboxConfig(BaseModel):
    """Configuration for creating a sandbox environment."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    language: SandboxLanguage = Field(
        default=SandboxLanguage.PYTHON, description="Programming language for execution"
    )
    machine_config: MachineConfig = Field(
        default=MachineConfig.DEFAULT, description="Compute resource configuration"
    )
    ttl_seconds: int = Field(
        default=3600, description="Time-to-live in seconds (max 14 days)"
    )
    display_name: str | None = Field(
        default=None, description="Human-readable name for the sandbox"
    )


class CodeExecutionRequest(BaseModel):
    """Request to execute code in a sandbox."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    code: str = Field(description="Python or JavaScript code to execute")
    input_files: list[SandboxFile] = Field(
        default_factory=list, description="Input files to make available"
    )
    ttl_extension_seconds: int | None = Field(
        default=None, description="Extend sandbox TTL by this amount"
    )


class CodeExecutionOutput(BaseModel):
    """Output from code execution."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    stdout: str = Field(default="", description="Standard output from execution")
    stderr: str = Field(default="", description="Standard error from execution")
    output_files: list[SandboxFile] = Field(
        default_factory=list, description="Files generated by execution"
    )
    execution_error: str | None = Field(
        default=None, description="Error message if execution failed"
    )


class DataProcessingResult(BaseModel):
    """Result from data processing in sandbox."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    summary: str = Field(description="Human-readable summary of the processed data")
    statistics: dict[str, Any] = Field(
        default_factory=dict, description="Statistical aggregations"
    )
    top_items: list[dict[str, Any]] = Field(
        default_factory=list, description="Top N items based on configured criteria"
    )
    total_count: int = Field(description="Total number of items processed")
    filtered_count: int = Field(
        default=0, description="Number of items after filtering"
    )
    truncated: bool = Field(
        default=False, description="Whether results were truncated due to size"
    )
    processing_metadata: dict[str, Any] = Field(
        default_factory=dict, description="Metadata about the processing"
    )


class MetricDescriptorSummary(BaseModel):
    """Summarized metric descriptor information."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    metric_type: str = Field(description="Full metric type path")
    display_name: str = Field(description="Human-readable name")
    description: str = Field(description="Metric description")
    metric_kind: str = Field(description="GAUGE, DELTA, or CUMULATIVE")
    value_type: str = Field(description="INT64, DOUBLE, BOOL, etc.")
    unit: str = Field(default="", description="Measurement unit")
    label_keys: list[str] = Field(
        default_factory=list, description="Available label keys"
    )


class TimeSeriesSummary(BaseModel):
    """Summarized time series information."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    metric_type: str = Field(description="Metric type")
    resource_type: str = Field(description="Resource type")
    resource_labels: dict[str, str] = Field(
        default_factory=dict, description="Resource identifying labels"
    )
    point_count: int = Field(description="Number of data points")
    min_value: float | None = Field(default=None, description="Minimum value")
    max_value: float | None = Field(default=None, description="Maximum value")
    avg_value: float | None = Field(default=None, description="Average value")
    latest_value: float | None = Field(default=None, description="Most recent value")
    latest_timestamp: str | None = Field(
        default=None, description="Timestamp of latest value"
    )


class LogEntrySummary(BaseModel):
    """Summarized log entry information for large result sets."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    severity_counts: dict[str, int] = Field(
        default_factory=dict, description="Count by severity level"
    )
    resource_type_counts: dict[str, int] = Field(
        default_factory=dict, description="Count by resource type"
    )
    top_error_messages: list[str] = Field(
        default_factory=list, description="Most frequent error messages"
    )
    time_range: dict[str, str] = Field(
        default_factory=dict, description="Earliest and latest timestamps"
    )
    sample_entries: list[dict[str, Any]] = Field(
        default_factory=list, description="Representative sample entries"
    )


# =============================================================================
# Sandbox Execution Events (for visibility/transparency)
# =============================================================================


class SandboxEventType(str, Enum):
    """Types of sandbox execution events."""

    SANDBOX_CREATED = "sandbox_created"
    SANDBOX_DELETED = "sandbox_deleted"
    CODE_EXECUTION_STARTED = "code_execution_started"
    CODE_EXECUTION_COMPLETED = "code_execution_completed"
    CODE_EXECUTION_FAILED = "code_execution_failed"
    DATA_LOADED = "data_loaded"
    OUTPUT_GENERATED = "output_generated"


class SandboxExecutionEvent(BaseModel):
    """Event emitted during sandbox execution for visibility.

    These events allow users to see what the sandbox is doing,
    providing transparency and building trust in the agent's actions.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    event_type: SandboxEventType = Field(description="Type of sandbox event")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 timestamp of the event",
    )
    execution_mode: str = Field(
        description="Execution mode: 'agent_engine', 'local', or 'fallback'"
    )
    sandbox_name: str | None = Field(
        default=None, description="Sandbox resource name (if applicable)"
    )
    code_snippet: str | None = Field(
        default=None, description="First 500 chars of code being executed"
    )
    input_data_summary: str | None = Field(
        default=None, description="Summary of input data (type, size)"
    )
    output_summary: str | None = Field(
        default=None, description="Summary of output (success/error, size)"
    )
    duration_ms: float | None = Field(
        default=None, description="Execution duration in milliseconds"
    )
    error_message: str | None = Field(
        default=None, description="Error message if execution failed"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional event metadata"
    )


class SandboxExecutionLog(BaseModel):
    """Complete log of sandbox execution for a single processing request.

    This provides a full audit trail of what happened during sandbox processing.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    request_id: str = Field(description="Unique identifier for this execution request")
    template_name: str | None = Field(
        default=None, description="Name of processing template used"
    )
    execution_mode: str = Field(
        description="Execution mode: 'agent_engine', 'local', or 'fallback'"
    )
    events: list[SandboxExecutionEvent] = Field(
        default_factory=list, description="Sequence of events during execution"
    )
    total_duration_ms: float = Field(
        default=0, description="Total execution duration in milliseconds"
    )
    success: bool = Field(default=False, description="Whether execution succeeded")
    input_item_count: int = Field(
        default=0, description="Number of items in input data"
    )
    output_item_count: int = Field(
        default=0, description="Number of items in output data"
    )
